### ISSUE TITLE
specifying languages?

### ISSUE THREAD

**Issue by jgreen4919** [jooyoungseo/youtubecaption#1]
I've got a list of video IDs from the same channel, almost all of which have English caption tracks when I go to the video page manually. When I iterate through the list of video IDs and call get_caption() to get the transcripts, some of the caption tracks come back in English but some others come back in Arabic, or with Chinese characters before the English content on each line. Is there a way to tell get_caption() to look for the English caption track in the function call?

I tried editing this line in get_caption():

reticulate::import("youtube_transcript_api")$YouTubeTranscriptApi$get_transcripts(list(vid))

to:

reticulate::import("youtube_transcript_api")$YouTubeTranscriptApi$get_transcripts(list(pvideos_dat$video_id[132]), languages = c('en'))

for videos that returned both English and non-English captions when going by the default, but they returned the same error (_probably_ the language codes I'm providing are invalid or they aren't supported by the video? but I'm not sure):

Error in py_call_impl(callable, dots$args, dots$keywords) : 
  CouldNotRetrieveTranscript: Could not get the transcript for the video https://www.youtube.com/watch?v=LrqDWmuAe-c! This usually happens if one of the following things is the case:
 - subtitles have been disabled by the uploader
 - none of the language codes you provided are valid
 - none of the languages you provided are supported by the video
 - the video is no longer available.

If none of these things is the case, please create an issue at https://github.com/jdepoix/youtube-transcript-api/issues

Detailed traceback: 
  File "/anaconda3/envs/R_youtube_caption/lib/python3.7/site-packages/youtube_transcript_api/_api.py", line 69, in get_transcripts
    raise exception
  File "/anaconda3/envs/R_youtube_caption/lib/python3.7/site-packages/youtube_transcript_api/_api.py", line 66, in get_transcripts
    data[video_id] = cls.get_transcript(video_id, languages, proxies)
  File "/anaconda3/envs/R_youtube_caption/lib/python3.7/site-packages/youtube_transcript_api/_api.py", line 95,

**Comment by holnburger** [comment]
Try to add the specifided language also as list. Instead of 
`reticulate::import("youtube_transcript_api")$YouTubeTranscriptApi$get_transcripts(list(pvideos_dat$video_id[132]), languages = c('en'))`

you should try:
`reticulate::import("youtube_transcript_api")$YouTubeTranscriptApi$get_transcripts(list(pvideos_dat$video_id[132]), languages = list('en'))`

This did work for me.

**Comment by jooyoungseo** [comment]
This issue has been addressed via 4184c03. Please install the development version; this update will be submitted to CRAN soon.

``` r
remotes::install_github("jooyoungseo/youtubecaption")
```
