### ISSUE TITLE
Error in get_caption

### ISSUE THREAD

**Issue by PedroSennaVieira** [jooyoungseo/youtubecaption#2]
the package youtubecaption was working perfectly, but now it returns the following error:

```
Error in value[[3L]](cond) : 
  Need to install Anaconda from https://www.anaconda.com/download/.
Error in system2(conda, args = c("info", "--json"), stdout = TRUE, stderr = FALSE) : 
  'CreateProcess' failed to run 'D:\Conda\condabin\conda.bat info --json'
```
I don't even understand why is it related to anaconda (although I have python and anaconda installed)... The code is:

```
library(youtubecaption)
a <- get_caption("https://www.youtube.com/watch?v=-7Kq5w_3AfY")
```

**Comment by jooyoungseo** [comment]
Thanks for filing the issue, @PedroSennaVieira.

I cannot reproduce the error on my machine. It works on my end as follows:

``` r
library(youtubecaption)
a <- get_caption("https://www.youtube.com/watch?v=-7Kq5w_3AfY")


head(a)
#> # A tibble: 6 x 5
#>   segment_id text                                     start duration vid        
#>        <int> <chr>                                    <dbl>    <dbl> <chr>      
#> 1          1 hideout and what save do we go for        0.51     4.13 -7Kq5w_3AfY
#> 2          2 two Indians power boom elephant two      15.6      6.25 -7Kq5w_3AfY
#> 3          3 archers let's do it                      19.9      4.56 -7Kq5w_3AfY
#> 4          4 ah he's a sticks elephant archers        21.9      5.16 -7Kq5w_3AfY
#> 5          5 don't work against Aztecs it was any     24.4      5.63 -7Kq5w_3AfY
#> 6          6 other sip I were gonna thumb two archers 27.0      6.50 -7Kq5w_3AfY

tail(a)
#> # A tibble: 6 x 5
#>   segment_id text                                     start duration vid        
#>        <int> <chr>                                    <dbl>    <dbl> <chr>      
#> 1        221 would have run into these gold miners as 1406.    15    -7Kq5w_3AfY
#> 2        222 well who is vv okay we have way more     1408.    16.9  -7Kq5w_3AfY
#> 3        223 food we had way more wood we had way     1421.     8.84 -7Kq5w_3AfY
#> 4        224 more stone we have way more gold so um   1425.     7.62 -7Kq5w_3AfY
#> 5        225 got more bills as well and we stock      1430.     5.76 -7Kq5w_3AfY
#> 6        226 would want to use a sort of make sense   1433.     3.29 -7Kq5w_3AfY
```

<sup>Created on 2020-04-26 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9001)</sup>

Would you mind providing me with some more details including the following information?:

1. Your OS info.
2. Current R version.
3. Please share the results of the conda path and version by using the following command in your terminal:

``` bash
where conda
conda --version
```

**Comment by PedroSennaVieira** [comment]
I have windows 10
R version 3.6.1
Where conda result: D:\Anaconda\Scripts\conda.exe
conda --version result: conda 4.8.2

**Comment by PedroSennaVieira** [comment]
it is worth mentioning that i uninstalled and installed several times and now the error is:

```
Error in value[[3L]](cond) : 
  Need to install Anaconda from https://www.anaconda.com/download/.
Error in system2(conda, args = c("info", "--json"), stdout = TRUE) : 
  'CreateProcess' failed to run 'D:\Anaconda\condabin\conda.bat info --json'
```

**Comment by PedroSennaVieira** [comment]
Could you discover what might be happening?

**Comment by jooyoungseo** [comment]
I am very sorry for this delayed response, @PedroSennaVieira.

Would you mind checking the following in your R console?

``` r
reticulate::py_available(initialize = TRUE)
```

If you see any error after the command, then please report the issue to `reticulate` GitHub repo.

In any event you do not have any error for the command above, please do the following and share your results with me.

Step 1. In your terminal (cmd.exe on Windows platform):

``` bash
# Check your conda environment list:
conda info --envs

# If you see `R_youtube_caption` in the list, type in the following command to remove the env:
conda remove --name R_youtube_caption --all -y
```

Step 2. In your R console:

``` r
if(!require(remotes)) {
install.packages("remotes")
}

remotes::install_github("rstudio/reticulate")
remotes::install_github("jooyoungseo/youtubecaption")

library(youtubecaption)
url <- "https://www.youtube.com/watch?v=cpbtcsGE0OA"
caption <- get_caption(url)
caption
```

Step 3. If step 2. throws any error, please remove any additional `Python` from your system (ideally, you need to have only `conda` installed on your system other than any additional python installer).

Step 4. After removing additional `python` except for `conda`, please go through step 1 and 2 again.

**Comment by PedroSennaVieira** [comment]
no problem at all, thank you very much for your assistance! I'm afraid it still did not solve the problem...
when I execute conda info --envs it does not show R_youtube_caption`.

Step 2 went smoothly except for remotes::install_github("jooyoungseo/youtubecaption")
I could only install youtube caption from cran (although it still installed some other packages.)

I executed step 3 and then tried everything else again...it's very weird...i did a lot of research and I also suspect that is a python problem... i had installed and uninstalled cond...cleaned the remaining folders... and I searched for other pythons and could not find any other version

**Comment by jooyoungseo** [comment]
Let me help you as much as I can. Would you mind sharing what your R console responds (i.e., results) to the following commands?

* Command 1:

``` r
reticulate::py_available(initialize = TRUE)
```

* Command 2:

``` r
remotes::install_github("jooyoungseo/youtubecaption")
```

Please fully share  each of the two commands with me so that I can understand what's wrong with your system.

Please use [reprex package](https://reprex.tidyverse.org/articles/articles/learn-reprex.html) to share any reproducible code and output with me. That way would best help me figure out the problems in greater detail.

**Comment by PedroSennaVieira** [comment]
Ok, i will learn the reprex, in the meanwhile


```
reticulate::py_available(initialize = TRUE)
[1] FALSE
```
I believe R is not being able to find my python...i did a lot of research and just could not solve...if this was ultimately crucial I would format the notebook... i just can't find a command to make reticulate point to the python...

the second command installed all packages without any issues

**Comment by jooyoungseo** [comment]
My gut feeling is that your anaconda `Python` is not added to your system path.

Please check if you have `python` in your system path by typing the following command in your `cmd.exe` terminal:

``` bash
python --version
```

If this is the case, please do that by consulting with the following resource:

* [Add Anaconda to Path (Optional)](https://www.datacamp.com/community/tutorials/installing-anaconda-windows#add-anaconda-to-path-optional-).

* [Here is video as well](https://www.youtube.com/watch?v=mf5u2chPBjY&feature=youtu.be&t=15m45s).

**Comment by PedroSennaVieira** [comment]
![image](https://user-images.githubusercontent.com/51272424/80927424-24b84400-8d74-11ea-86c6-7416c4eea408.png)

**Comment by PedroSennaVieira** [comment]
i added them to path like in the video...nevertheless, get_caption still does not work...

**Comment by PedroSennaVieira** [comment]
somehow i think reticulate is not able to identify the python...
when I read the get_capion one of the lines is:

`reticulate::conda_create(envnm, packages = c("python=3.7.3"), `

my python is 3.7.6...is that a problem?

**Comment by PedroSennaVieira** [comment]
Here i generated with reprex:

```
envnm="teste"                                     
reticulate::conda_create(envnm, packages = c("python=3.7.6"), 
                         conda = "auto") 
#> Warning in system2(conda, shQuote(args)): 'CreateProcess' failed to
#> run 'D:\Anaconda\condabin\conda.bat "create" "--yes" "--name" "teste"
#> "python=3.7.6"'
#> Error: Error 127 occurred creating conda environment teste
```

**Comment by jooyoungseo** [comment]
> somehow i think reticulate is not able to identify the python...
> when I read the get_capion one of the lines is:
> 
> `reticulate::conda_create(envnm, packages = c("python=3.7.3"), `
> 
> my python is 3.7.6...is that a problem?

I don't think the different python version should be an issue because I have made `youtubecaption` as a separate virtual conda environment independent of users' python version. Would you mind filing your issue to [reticulate repo](https://github.com/rstudio/reticulate/issues)? I am carefully asking this because I do not think the issue you are having now can be further addressed on my end; rather, it has to do with `reticulate`. I am very sorry that I was not of any big help in solving this issue.

**Comment by PedroSennaVieira** [comment]
no problem at all! i thank you anyway for all the help...i really believe I must have corrupted some file and it must be the case of formatting the laptop
