### ISSUE TITLE
tryCatch(get_caption()) in loop

### ISSUE THREAD

**Issue by jbisbee1** [jooyoungseo/youtubecaption#3]
Hi, 

I'm downloading captions for thousands of videos, some of which disable subtitles. Typically, I would wrap the get_caption() function in a tryCatch() and loop over the thousands of videos, skipping to the next when there is an error. However, tryCatch() doesn't seem to work with get_caption(), possibly because it's built on Python. Is there a way to save "captions are disabled" errors without breaking a loop?

Warmly,
Jim

**Comment by jooyoungseo** [comment]
Thanks for using the package, @jbisbee1. I assume that the issue does not have to do with Python-side error.

I recommend you try the following approach.

``` r
library(tidyverse)
library(youtubecaption)

# Make your video list:
video_list <- list()

# Safely loop through each video and save it to a new variable:
captioned_data <- video_list %>%
  map(safely(get_caption))

# Examine the structure of the saved data:
str(captioned_data)
```

`captioned_data$result` will only contain the processed data while all the error messages will be saved into `captioned_data$error`.

You can find more examples how to use `safely()` by reading [dealing with failure chapter](https://r4ds.had.co.nz/iteration.html#dealing-with-failure) of Hadley's book.

**Comment by jooyoungseo** [comment]
I am closing this unless there is any further issue.
